version: '3'

services:
  php:
    build: .
    volumes: 
      - ./:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:

